name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # آپلود سورس به سرور (بدون .git / node_modules / .next)
      - name: Upload project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/deploy/apps/ranandeh"
          overwrite: true
          rm: true
          exclude: ".git,.github,node_modules,.next"

      # نصب پکیج‌ها، بیلد و ری‌استارت سرویس
      - name: Build & restart on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /home/deploy/apps/ranandeh
            npm ci --omit=dev
            npm run build
            sudo systemctl restart ranandeh
            systemctl --no-pager --full status ranandeh | head -n 25
